[package]
name = "notifier"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sway-notifier"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "4.11.0"
