[package]
name = "statusline"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sway-statusline"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
sysinfo = "0.30.7"

