# Author: Alexander Brevig <alexanderbrevig@gmail.com>, krfl <kr.fl@outlook.com>
# Adopted from https://github.com/biletskyy/flatwhite-syntax
# Themes guide https://github.com/helix-editor/helix/blob/master/book/src/themes.md

# Gutter
"hint" = { fg = "base1", bg = "base5" }
"info" = { fg = "base1", bg = "base5" }
"warning" = { fg = "orange_text", bg = "orange_bg" }
"error" = { fg = "red_text", bg = "red_bg" }
# Editor area
"diagnostic" = { fg = "base1", bg = "base5" }
"diagnostic.hint" = { fg = "base1", bg = "base5" }
"diagnostic.info" = { fg = "base1", bg = "base5" }
"diagnostic.warning" = { fg = "orange_text", bg = "orange_bg" }
"diagnostic.error" = { fg = "red_text", bg = "red_bg" }
"diagnostic.unnecessary" = { fg = "base3" }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

"ui.background" = { fg = "base1", bg = "base7" }
# "ui.background.separator" = {}  # Picker separator below input line
"ui.window" = { fg = "base1", bg = "base6" }  # Borderlines separating splits
"ui.gutter" = { fg = "base1", bg = "base7" }
"ui.gutter.selected" = {}  # Gutter for the line the cursor is on
"ui.text" = { fg = "base1" }
"ui.text.focus" = { modifiers = ["bold"] }  # The currently selected line in the picker
# "ui.text.info" = {}  # The key: command text in ui.popup.info boxes
"ui.text.inactive" = { fg = "base3" }
"ui.cursor" = { fg = "base6", bg = "base3" }
"ui.cursor.primary" = { fg = "base7", bg = "base1" }
"ui.cursor.insert" = { fg = "base7", bg = "base1" }
"ui.cursor.select" = { fg = "base7", bg = "base1" }
"ui.cursor.match" = { fg = "base2", bg = "base4" }  #	Matching bracket etc.
"ui.selection" = { fg = "base2", bg = "base4" }
"ui.selection.primary" = { fg = "base1", bg = "base4" }
"ui.linenr" = { fg = "base1", bg = "base6" }
"ui.linenr.selected" = { fg = "base7", bg = "base1" }
"ui.virtual" = {}
"ui.virtual.ruler" = { bg = "base6" }
"ui.virtual.whitespace" = {}
"ui.virtual.indent-guide" = {}
"ui.virtual.inlay-hint" = {}
"ui.virtual.inlay-hint.parameter" = {}
"ui.virtual.inlay-hint.type" = {}
"ui.virtual.wrap" = {}
"ui.virtual.jump-label" = {}
"ui.bufferline" = { fg = "base1", bg = "base5" }
"ui.bufferline.active" = { fg = "base7", bg = "base1", modifiers = ["bold"] }
"ui.statusline" = { fg = "base7", bg = "base1", modifiers = ["bold"] }
"ui.statusline.inactive" = { fg = "base1", bg = "base5" }
"ui.statusline.normal" = {}
"ui.statusline.insert" = {}
"ui.statusline.select" = {}
"ui.statusline.separator" = {}
"ui.help" = { fg = "base1", bg = "base6" }  # Description box for commands
"ui.highlight" = { fg = "base1", bg = "base6" }  # Highlighted lines in the picker preview
"ui.menu" = { fg = "base1", bg = "base6" }  # Code and command completion menus
"ui.menu.selected" = { fg = "base6", bg = "base1" }  # Selected autocomplete item
"ui.menu.scroll" = { fg = "base4", bg = "base6" }  # fg sets thumb color, bg sets track color of scrollbar
"ui.popup" = { fg = "base1", bg = "base6" }  # Documentation popups (e.g. Space + k)
# "ui.popup.info" = {}  # Prompt for multiple key options (e.g. Space)
"ui.cursorline.primary" = { bg = "base6" }
"ui.cursorline.secondary" = { bg = "base6" }
"ui.cursorcolumn.primary" = { bg = "base6" }
"ui.cursorcolumn.secondary" = { bg = "base6" }

"attribute" = {}  # Class attributes, HTML tag attributes
"type" = { fg = "teal_text", bg = "teal_bg" }
# "type.builtin" = {}  # Primitive types provided by the language (int, usize)
# "type.parameter" = {}  # Generic type parameters (T)
# "type.enum.variant" = {}
"constructor" = {}
"constant" = { fg = "blue_text", bg = "blue_bg" }
# "constant.builtin" = {}  # Special constants provided by the language (true, false, nil etc)
# "constant.builtin.boolean" = {}
# "constant.character" = { fg = "green_text", bg = "green_bg" }
"constant.character.escape" = { fg = "orange_text", bg = "orange_bg" }
"constant.numeric" = { fg = "blue_text", bg = "blue_bg" }
# "constant.numeric.integer" = {}
# "constant.numeric.float" = {}
"string" = { fg = "green_text", bg = "green_bg" }
# "string.regexp" = {}
# "string.special" = {}
# "string.special.path" = {}
# "string.special.url" = {}
# "string.special.symbol" = {}
"comment" = { fg = "base3" }
# "comment.line" = {}
# "comment.block" = {}
# "comment.block.documentation" = {}
"variable" = {}
"variable.builtin" = {}  # Reserved language variables (self, this, super, etc.)
"variable.parameter" = {}  #  Function parameters
"variable.other.member" = {}  #  Fields of composite data types (e.g. structs, unions)
"label" = {}
# "punctuation" = {}
# "punctuation.delimiter" = {}  # Commas, colons
# "punctuation.bracket" = {}  # Parentheses, angle brackets, etc.
"punctuation.special" = { modifiers = ["bold"] }  # String interpolation brackets.
"keyword" = { fg = "purple_text", bg = "purple_bg" }
# "keyword.control" = {}
# "keyword.control.conditional" = {}  # if, else
# "keyword.control.repeat" = {}  # for, while, loop
# "keyword.control.import" = {}  # import, export
# "keyword.control.return" = {}
# "keyword.control.exception" = {}
# "keyword.operator" = {}  # or, in
# "keyword.directive" = {}
# "keyword.function" = {}
# "keyword.storage" = {}  # Keywords describing how things are stored
# "keyword.storage.type" = {}  # The type of something, class, function, var, let, etc.
# "keyword.storage.modifier" = {}  # Storage modifiers like static, mut, const, ref, etc.
# "operator" = {}  # ||, +=, >, etc.
# "function" = {}
# "function.builtin" = {}
# "function.method" = {}
# "function.macro" = {}
# "function.special" = {}
"tag" = { fg = "purple_text", bg = "purple_bg" }  # Tags (e.g. <body> in HTML)
"namespace" = {}
"special" = { fg = "blue_text", bg = "blue_bg" }  # Search match in picker
"property" = {}

"markup.heading" = { fg = "purple_text", bg = "purple_bg" }
# "markup.heading.marker" = {}
# "markup.heading.1" = {}
# "markup.heading.2" = {}
# "markup.heading.3" = {}
# "markup.heading.4" = {}
# "markup.heading.5" = {}
# "markup.heading.6" = {}
"markup.list" = { modifiers = ["bold"] }
# "markup.list.numbered" = {}
# "markup.list.unnumbered" = {}
# "markup.list.checked" = {}
# "markup.list.unchecked" = {}
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link" = { fg = "blue_text", bg = "blue_bg" }
"markup.link.url" = { fg = "blue_text", bg = "blue_bg", underline = { color = "blue_text", style = "line" } }
# "markup.link.label" = {}  # non-URL link references
"markup.link.text" = { fg = "green_text", bg = "green_bg" }
"markup.quote" = {}
"markup.raw" = {}
"markup.raw.inline" = {}
"markup.raw.block" = {}
"diff.plus" = {}
"diff.minus" = {}
"diff.delta" = {}
"diff.delta.moved" = {}
"diff.delta.conflict" = {}

[palette]
base1 = "#605a52"
base2 = "#93836c"
base3 = "#b9a992"
base4 = "#dcd3c6"
base5 = "#e4ddd2"
base6 = "#f1ece4"
base7 = "#f7f3ee"
accent = "#6a4cff"
orange_text = "#5b5143"
orange_text_sec = "#957f5f"
orange_bg = "#f7e0c3"
green_text = "#525643"
green_text_sec = "#81895d"
green_bg = "#e2e9c1"
teal_text = "#465953"
teal_text_sec = "#5f8c7d"
teal_bg = "#d2ebe3"
blue_text = "#4c5361"
blue_text_sec = "#7382a0"
blue_bg = "#dde4f2"
purple_text = "#614c61"
purple_text_sec = "#9c739c"
purple_bg = "#f1ddf1"
red_text = "#8D3D3D"
red_text_sec = "#B85959"
red_bg = "#FFD7D7"
diff_add = "#2db448"
diff_change = "#f2a60d"
diff_change_dark = "#795306"
diff_delete = "#ff1414"
diff_renamed = "#52aeff"
white = "#ffffff"

