# ~/src/helix/runtime/themes/flatwhite.toml
inherits = "flatwhite"

"comment" = { fg = "base3", modifiers = ["italic"] }
"comment.line" = { fg = "base3", modifiers = ["italic"] }
"comment.block" = { fg = "base3", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "base3", modifiers = ["italic"] }
"operator" = { fg = "base1" }
"type" = { fg = "teal_text", bg = "teal_bg" }
"variable" = { fg = "base1" }
"variable.builtin" = { fg = "teal_text", bg = "teal_bg" }
"variable.parameter" = { fg = "base1" }

"markup.heading" = { fg = "purple_text", bg = "purple_bg", modifiers = ["bold"] }
"markup.raw" = { fg = "orange_text", bg = "orange_bg" }
"markup.raw.inline" = { fg = "orange_text", bg = "orange_bg" }
"markup.raw.block" = {}
"markup.list" = { modifiers = ["bold"]}

"ui.bufferline" = { fg = "base1", bg = "base6" }
"ui.bufferline.active" = { fg = "base7", bg = "base1", modifiers = ["bold"] }

"ui.background" = { fg = "base1", bg = "base7" }
"ui.cursorline" = { bg = "base6" }

"ui.cursor" = { fg = "base1", bg = "base4" }
"ui.cursor.primary" = { fg = "base7", bg = "base1"  }
"ui.cursor.primary.insert" = { fg = "base1", bg = "base4" }
"ui.cursor.primary.select" = { fg = "base1", bg = "base4" }
"ui.cursor.match" = { fg = "base3", bg = "base5" }

"ui.selection" = { fg = "base1", bg = "base4" }
"ui.selection.primary" = { fg = "base7", bg = "base1" }

"ui.linenr" = { fg = "base1", bg = "base6" }
"ui.linenr.selected" = { fg = "base7", bg = "base1"  }

"ui.menu" = { fg = "base1", bg = "base6" }
"ui.menu.selected" = { fg = "base7", bg = "base1" }

"ui.statusline.inactive" = { fg = "base1", bg = "base5" }

