# Theme using the 16 terminal colors.
# https://github.com/helix-editor/helix/blob/master/book/src/themes.md

"hint"                   = "blue"
"info"                   = "blue"
"warning"                = "yellow"
"error"                  = "red"
"diagnostic"             = {}
"diagnostic.hint"        = {}
"diagnostic.info"        = {}
"diagnostic.warning"     = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error"       = { underline = { color = "red", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated"  = { modifiers = ["crossed_out"] }

"ui.background"                   = {}
"ui.background.separator"         = {}                                                   # Picker separator below input line
"ui.window"                       = {}                                                   # Borderlines separating splits
"ui.gutter"                       = {}
"ui.gutter.selected"              = {}                                                   # Gutter for the line the cursor is on
"ui.text"                         = {}
"ui.text.focus"                   = { modifiers = ["bold"] }                             # The currently selected line in the picker
"ui.text.info"                    = {}                                                   # The key: command text in ui.popup.info boxes
"ui.text.inactive"                = {}
"ui.cursor"                       = { modifiers = ["reversed"] }
"ui.cursor.match"                 = { fg = "white", bg = "gray" }                        #	Matching bracket etc.
"ui.selection"                    = { bg = "gray" }
"ui.linenr"                       = { modifiers = ["dim"] }
"ui.linenr.selected"              = {}
"ui.virtual"                      = {}
"ui.virtual.ruler"                = {}
"ui.virtual.whitespace"           = {}
"ui.virtual.indent-guide"         = {}
"ui.virtual.inlay-hint"           = {}
"ui.virtual.inlay-hint.parameter" = {}
"ui.virtual.inlay-hint.type"      = {}
"ui.virtual.wrap"                 = {}
"ui.virtual.jump-label"           = {}
"ui.bufferline"                   = { fg = "white", bg = "black" }
"ui.bufferline.active"            = { fg = "black", bg = "white", modifiers = ["bold"] }
"ui.statusline"                   = { fg = "black", bg = "white", modifiers = ["bold"] }
"ui.statusline.inactive"          = { fg = "white", bg = "black", modifiers = ["bold"] }
"ui.help"                         = {}                                                   # Description box for commands
"ui.highlight"                    = { bg = "gray" }                                      # Highlighted lines in the picker preview
"ui.menu"                         = {}                                                   # Code and command completion menus
"ui.menu.selected"                = { modifiers = ["reversed"] }                         # Selected autocomplete item
"ui.menu.scroll"                  = {}                                                   # fg sets thumb color, bg sets track color of scrollbar
"ui.popup"                        = {}                                                   # Documentation popups (e.g. Space + k)
"ui.popup.info"                   = {}                                                   # Prompt for multiple key options (e.g. Space)
"ui.cursorline.primary"           = {}
"ui.cursorline.secondary"         = {}
"ui.cursorcolumn.primary"         = {}
"ui.cursorcolumn.secondary"       = {}

"attribute"                 = {}                                      # Class attributes, HTML tag attributes
"type"                      = "cyan"
"constructor"               = "cyan"
"constant"                  = "default"
"constant.builtin"          = "green"                                 # Special constants provided by the language (true, false, nil etc)
"constant.character"        = "yellow"
"constant.character.escape" = "yellow"
"constant.numeric"          = "green"
"string"                    = "yellow"
"string.regexp"             = {}
"string.special"            = {}
"string.special.path"       = {}
"string.special.url"        = {}
"string.special.symbol"     = {}
"comment"                   = { modifiers = ["dim", "italic"] }
"variable"                  = "default"
"label"                     = {}
"punctuation"               = "default"
"punctuation.delimiter"     = { fg = "default", modifiers = ["dim"] } # Commas, colons
"punctuation.bracket"       = {}                                      # Parentheses, angle brackets, etc.
"punctuation.special"       = "magenta"                               # String interpolation brackets.
"keyword"                   = "blue"
"operator"                  = "magenta"                               # ||, +=, >, etc.
"function"                  = {}
"function.builtin"          = {}
"function.method"           = {}
"function.macro"            = {}
"function.special"          = {}
"tag"                       = "cyan"                                  # Tags (e.g. <body> in HTML)
"namespace"                 = {}
"special"                   = "green"                                 # Search match in picker
"property"                  = {}

"markup.heading"       = "magenta"
"markup.list"          = { modifiers = ["bold"] }
"markup.bold"          = { modifiers = ["bold"] }
"markup.italic"        = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link"          = { underline = { style = "line" } }
"markup.link.url"      = { underline = { style = "line" } }
"markup.link.label"    = { underline = { style = "line" } } # non-URL link references
"markup.link.text"     = {}
"markup.quote"         = {}
"markup.raw"           = {}
"markup.raw.inline"    = "yellow"
"markup.raw.block"     = {}

"diff.plus"           = "green"
"diff.minus"          = "red"
"diff.delta"          = "yellow"
"diff.delta.conflict" = "magenta"
