# Colors (Snazzy)

# Default colors
[colors.primary]
background = '#282a36'
foreground = '#eff0eb'

# Normal colors
[colors.normal]
black   = '#282a36'
red     = '#ff5c57'
green   = '#5af78e'
yellow  = '#f3f99d'
blue    = '#57c7ff'
magenta = '#ff6ac1'
cyan    = '#9aedfe'
white   = '#eff0eb'

# Bright colors
[colors.bright]
black   = '#686868'
red     = '#ff5c57'
green   = '#5af78e'
yellow  = '#f3f99d'
blue    = '#57c7ff'
magenta = '#ff6ac1'
cyan    = '#9aedfe'
white   = '#eff0eb'

[font]
size = 11.0

[font.normal]
family = "Fira Code"
