# Helix editor configuration
# https://docs.helix-editor.com/configuration.html

theme = "monokai_pro_custom"

[editor]
scrolloff = 8
cursorline = true
line-number = "relative"
bufferline = "multiple"
gutters = ["spacer", "diagnostics", "spacer", "line-numbers", "spacer"]
rulers = [80, 120]
popup-border = "all"
completion-timeout = 5
completion-replace = false
mouse = false
shell = ["fish", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = []
right = ["diagnostics", "register", "position", "total-line-numbers", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

# https://docs.helix-editor.com/remapping.html
# https://github.com/helix-editor/helix/blob/master/helix-term/src/commands.rs#L250
[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-a = "select_all"
C-r = "redo"
C-d = ["extend_to_line_bounds", "yank", "open_below", "normal_mode", "replace_with_yanked", "collapse_selection"]
C-u = "no_op"
A-h = "goto_previous_buffer"
A-l = "goto_next_buffer"
A-q = ":buffer-close"
q = "no_op"
Q = "no_op"
x = "select_line_below"
X = "select_line_above"
Y = ["extend_to_line_bounds", "yank"]
D = ["extend_to_line_bounds", "delete_selection"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.select]
C-d = ["search_selection", "extend_search_next"]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
