theme = "flatwhite"

[editor]
scrolloff = 8
cursorline = true
popup-border = "all"
completion-timeout = 5
completion-replace = true
rulers = [120]
mouse = false
shell = ["fish", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"

C-r = "redo"
