# Helix editor configuration
# https://docs.helix-editor.com/configuration.html

theme = "rose_pine_dawn"

[editor]
scrolloff = 8
cursorline = true
popup-border = "all"
completion-timeout = 5
completion-replace = false
rulers = [120]
mouse = false
shell = ["fish", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "spacer", "version-control"]
center = []
right = ["diagnostics", "selections", "register", "position", "total-line-numbers", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# https://docs.helix-editor.com/remapping.html
# https://github.com/helix-editor/helix/blob/master/helix-term/src/commands.rs
[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
