# Helix editor configuration
# https://docs.helix-editor.com/configuration.html

theme = "rose_pine"

[editor]
scrolloff = 9999
cursorline = true
line-number = "relative"
bufferline = "multiple"
rulers = [80, 120]
gutters = ["spacer", "diagnostics", "spacer", "line-numbers", "spacer"]
popup-border = "all"
completion-timeout = 5
completion-replace = false
mouse = false
shell = ["fish", "-c"]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = []
right = ["diagnostics", "register", "position", "total-line-numbers", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0

# https://docs.helix-editor.com/remapping.html
# Find commands and their keybindings with space-?
[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-a = "select_all"
C-r = "redo"
C-d = ["extend_to_line_bounds", "yank", "paste_after", "collapse_selection"]
C-u = "no_op"
A-h = "goto_previous_buffer"
A-l = "goto_next_buffer"
A-q = ":buffer-close"
A-tab = "goto_last_accessed_file"
q = "no_op"
Q = "no_op"
x = "select_line_below"
X = "select_line_above"
Y = ["extend_to_line_bounds", "yank"]
D = ["extend_to_line_bounds", "delete_selection"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.select]
C-d = ["search_selection", "extend_search_next"]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
